### ISSUE TITLE
请问怎么获取openid

### ISSUE THREAD

**Issue by 1002679811** [binarywang/weixin-java-mp-demo-springmvc#11]
我在项目中想发送客服消息  用这个类TestConfigStorage想获取openid，但一启动项目就报错，还有要获取关注公众号的全部openid  怎么操作

**Comment by binarywang** [comment]
看你需要在什么场合获取openid，有网页授权，还有通过后端交互也能拿到。
获取关注的全部openid的接口userService里有方法

**Comment by 1002679811** [comment]
感谢  可以关闭了
