### ISSUE TITLE
我是用的测试号做的测试 群发文本消息没问题 群发图文消息 会提示48008 没权限，这是什么问题。  

### ISSUE THREAD

**Issue by 1002679811** [binarywang/weixin-java-mp-demo-springmvc#12]
还有群发文本消息 是不是不能短时间内重复发送，我已经设置了setClientMsgId这个值了  但还是会被限制住，不能重复群发信息

**Comment by 1002679811** [comment]
{"errcode":48008,"errmsg":"no permission for this msgtype hint: [RkZu30973ge31]"}这是报错语句，图片上传返回的MediaId也拿到了。massMessage.setMsgType(WxConsts.MassMsgType.MPNEWS);就是这里的type设置成MPNEWS  就报没权限了

**Comment by binarywang** [comment]
那就是没权限了
