### ISSUE TITLE
WxMpConfig使用@Value问题

### ISSUE THREAD

**Issue by kylinshaw** [binarywang/weixin-java-mp-demo-springmvc#13]
情况是这样的，@Value("#{wxProperties.wx_token}")注解使用的时候一直报错，Property or field 'WxMpConfig' cannot be found on object of type 'org.springframework.beans.factory.config.BeanExpressionContext' - maybe not public?
面向google找到好久，有人说用$代替#，试了一下，还真行了，这是个什么问题？

**Comment by binarywang** [comment]
我刚测试了下，本demo是没有问题的，可以注入并取得对应的值，不知道你改了什么东西。

**Comment by kylinshaw** [comment]
> 我刚测试了下，本demo是没有问题的，可以注入并取得对应的值，不知道你改了什么东西。

我没有直接使用demo工程，是自己搭的工程，修改的地方还是比较多了，不知道这个$#的问题和什么有关系

**Comment by binarywang** [comment]
你需要自己仔细排查下了
