### ISSUE TITLE
获取草稿内容接口

### ISSUE THREAD

**Issue by histjxg** [binarywang/weixin-java-mp-demo-springmvc#24]
获取草稿内容接口可以新增一个字段
即WxMpDraftArticles类新加一个字段thumbUrl,设置封面素材接口

**Comment by binarywang** [comment]
欢迎直接提交PR修复该问题，另外涉及到WxJava的修改，请到WxJava项目提交问题，谢谢

**Comment by binarywang** [comment]
最新版本其实已经添加了
