### ISSUE TITLE
你好请问    微信模板消息的发送的接口吗？

### ISSUE THREAD

**Issue by eratel** [binarywang/weixin-java-mp-demo-springmvc#6]
你好请问    微信模板消息的发送的接口吗？

**Comment by binarywang** [comment]
请查阅主项目的wiki

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/weixin-java-tools/wiki/MP_%E5%8F%91%E9%80%81%E6%A8%A1%E6%9D%BF%E6%B6%88%E6%81%AF
