### ISSUE TITLE
请问controller相关的问题

### ISSUE THREAD

**Issue by LorenzosSummer** [binarywang/weixin-java-mp-demo-springmvc#7]
WxMpPortalController是在哪里被使用的？
如何使用WxMenuController相关的代码？（我的测试公众号没有生成菜单）

**Comment by binarywang** [comment]
portal对应的地址要设在微信公众号后台里，menu的需要自己手动调用

**Comment by LorenzosSummer** [comment]
感谢up主回复，我在initserver中调用menu报空指针，请问下要在哪里调呢？

**Comment by binarywang** [comment]
菜单是需要一次性运行就可以了，不要试图启动时就自动创建菜单。
自己调用menu的controller相关方法对应的url即可

**Comment by LorenzosSummer** [comment]
感谢大大支持，问题已解决
